#!/bin/bash

pkill eww
pkill python

eww daemon
eww open bar
eww open dock
eww open notifications_popup
eww open wallpaper
python $XDG_CONFIG_HOME/eww/scripts/apps.py --query
python $XDG_CONFIG_HOME/eww/scripts/notifications.py --init
